### ISSUE TITLE
Unable to retrieve MLFlow logged param from Experiment Run 

### ISSUE THREAD

**Issue by jakeatmsft** [Azure/azureml-examples#1123]
## Which example? Describe the issue

example: azureml-examples/cli/jobs/single-step/dask/nyctaxi/src/startDask.py
description:
Params logged using MLFlow show up in Run details in Azure Portal, however when retrieving run details I do not see params logged.

Azure portal:
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/47987698/162327881-e079e7ce-f047-4bb1-8f0d-c478959e1f5b.png">

output from run.get_details():

{'runId': '81160342-cabb-4253-a774-03c672960252',
 'target': 'dask-ds2',
 'status': 'Canceled',
 'startTimeUtc': '2022-04-07T19:01:34.968669Z',
 'endTimeUtc': '2022-04-07T21:43:18.477897Z',
 'services': {},
 'properties': {'_azureml.ComputeTargetType': 'amlctrain',
  'ContentSnapshotId': 'a60eeaf9-af8d-44c6-be79-0da8c2e737ee',
  'ProcessInfoFile': 'azureml-logs/process_info.json',
  'ProcessStatusFile': 'azureml-logs/process_status.json'},
 'inputDatasets': [],
 'outputDatasets': [{'identifier': {'savedId': '7c5d6a0e-c77f-4cc6-b2d6-31ded109e680'},
   'outputType': 'RunOutput',
   'outputDetails': {'outputName': 'output_folder'},
   'dataset': {
     "source": [
       "('workspaceblobstore', 'dataset/81160342-cabb-4253-a774-03c672960252/output_folder/')"
     ],
     "definition": [
       "GetDatastoreFiles"
     ],
     "registration": {
       "id": "7c5d6a0e-c77f-4cc6-b2d6-31ded109e680",
       "name": null,
       "version": null,
       "workspace": "Workspace.create(name='wu2modtimesmlsw', subscription_id='7fd76d0f-84f2-498b-a997-e0d059af5ce1', resource_group='wu2modtimerg')"
     }
   }}],
 'runDefinition': {'script': None,
  'command': 'python startDask.py --output_folder ${{outputs.output_folder}}',
  'useAbsolutePath': True,
  'arguments': [],
  'sourceDirectoryDataStore': None,
  'framework': 'PyTorch',
  'communicator': 'Nccl',
  'target': 'dask-ds2',
  'dataReferences': {},
  'data': {},
  'outputData': {'output_folder': {'outputLocation': None,
    'mechanism': 'Mount',
    'additionalOptions': None,
    'environmentVariableName': None}},
  'datacaches': [],
  'jobName': None,
  'maxRunDurationSeconds': None,
  'nodeCount': 3,
  'instanceTypes': [],
  'priority': None,
  'credentialPassthrough': False,
  'identity': None,
  'environment': {'name': 'startDask',
   'version': '2',
   'assetId': 'azureml://locations/westus2/workspaces/dc720ed6-90b3-49cb-8383-0897f5db4402/environments/startDask/versions/2',
   'python': {'interpreterPath': 'python',
    'userManagedDependencies': False,
    'condaDependencies': {'channels': ['defaults', 'conda-forge'],
     'dependencies': ['python=3.7',
      'dask==2021.8.1',
      'distributed==2021.8.1',
      'pip==21.3.1',
      'adlfs==2021.10.0',
      'jupyterlab',
      'jupyter-server-proxy',
      {'pip': ['ray[tune]==1.9.2',
        'ray[rllib]==1.9.2',
        'ray[serve]==1.9.2',
        'xgboost_ray==0.1.6',
        'dask==2021.12.0',
        'pyarrow >= 5.0.0',
        'fsspec==2021.10.1',
        'fastparquet==0.7.2',
        'tabulate==0.8.9',
        'azureml-mlflow',
        'prophet']}],
     'name': 'azureml_f5db19dc19d246abd88f1190cc9c2415'},
    'baseCondaEnvironment': None},
   'environmentVariables': {'EXAMPLE_ENV_VAR': 'EXAMPLE_VALUE'},
   'docker': {'baseImage': 'mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04',
    'platform': {'os': 'Linux', 'architecture': 'amd64'},
    'baseDockerfile': None,
    'baseImageRegistry': {'address': None, 'username': None, 'password': None},
    'enabled': False,
    'arguments': []},
   'spark': {'repositories': [], 'packages': [], 'precachePackages': True},
   'inferencingStackVersion': None},
  'history': {'outputCollection': True,
   'directoriesToWatch': ['logs'],
   'enableMLflowTracking': True},
  'spark': {'configuration': {}},
  'parallelTask': {'maxRetriesPerWorker': 0,
   'workerCountPerNode': 1,
   'terminalExitCodes': None,
   'configuration': {}},
  'amlCompute': {'name': None,
   'vmSize': None,
   'retainCluster': False,
   'clusterMaxNodeCount': None},
  'aiSuperComputer': {'instanceType': 'D2',
   'imageVersion': 'pytorch-1.7.0',
   'location': None,
   'aiSuperComputerStorageData': None,
   'interactive': False,
   'scalePolicy': None,
   'virtualClusterArmId': None,
   'tensorboardLogDirectory': None,
   'sshPublicKey': None,
   'sshPublicKeys': None,
   'enableAzmlInt': True,
   'priority': 'Medium',
   'slaTier': 'Standard',
   'userAlias': None},
  'kubernetesCompute': {'instanceType': None},
  'tensorflow': {'workerCount': 0, 'parameterServerCount': 0},
  'mpi': {'processCountPerNode': 0},
  'pyTorch': {'communicationBackend': 'Nccl', 'processCount': 3},
  'hdi': {'yarnDeployMode': 'None'},
  'containerInstance': {'region': None, 'cpuCores': 2.0, 'memoryGb': 3.5},
  'exposedPorts': None,
  'docker': {'useDocker': True,
   'sharedVolumes': True,
   'shmSize': '2g',
   'arguments': []},
  'cmk8sCompute': {'configuration': {}},
  'commandReturnCodeConfig': {'returnCode': 'Zero',
   'successfulReturnCodes': []},
  'environmentVariables': {},
  'applicationEndpoints': {},
  'parameters': []},
 'logFiles': {'azureml-logs/55_azureml-execution-tvmps_5987e3d904c1b9ce843a5fc9569bf1847092b85d2f71b2906bffe3df00ad9435_d.txt': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/azureml-logs/55_azureml-execution-tvmps_5987e3d904c1b9ce843a5fc9569bf1847092b85d2f71b2906bffe3df00ad9435_d.txt?sv=2019-07-07&sr=b&sig=BFat4nhGOZxYjsFrZXGeRoUlx192sbwUT3SBMxLDF1M%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A15%3A37Z&ske=2022-04-09T02%3A25%3A37Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'azureml-logs/55_azureml-execution-tvmps_7318e771e68051077c6cf6cae224b662fda60c42f523e4e4711fabcb812b1884_d.txt': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/azureml-logs/55_azureml-execution-tvmps_7318e771e68051077c6cf6cae224b662fda60c42f523e4e4711fabcb812b1884_d.txt?sv=2019-07-07&sr=b&sig=lkczqkYG08WHUm4m71em7jU7kgvCH1OfC9fRV3VVEco%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A15%3A37Z&ske=2022-04-09T02%3A25%3A37Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'azureml-logs/55_azureml-execution-tvmps_f811095d9dad2cc3c9a1c3b2eac109b550c7207bb242244e87ca3f157926e76e_d.txt': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/azureml-logs/55_azureml-execution-tvmps_f811095d9dad2cc3c9a1c3b2eac109b550c7207bb242244e87ca3f157926e76e_d.txt?sv=2019-07-07&sr=b&sig=WHOmEEvA51q%2Bp77oAyFBqRoFUN%2BVVFACGBboLbp6L9I%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A15%3A37Z&ske=2022-04-09T02%3A25%3A37Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'azureml-logs/65_job_prep-tvmps_5987e3d904c1b9ce843a5fc9569bf1847092b85d2f71b2906bffe3df00ad9435_d.txt': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/azureml-logs/65_job_prep-tvmps_5987e3d904c1b9ce843a5fc9569bf1847092b85d2f71b2906bffe3df00ad9435_d.txt?sv=2019-07-07&sr=b&sig=EkFQocQLR%2FGyjfw0QZ9z36SipFofeckxTv9AWMF1qig%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A15%3A37Z&ske=2022-04-09T02%3A25%3A37Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'azureml-logs/65_job_prep-tvmps_7318e771e68051077c6cf6cae224b662fda60c42f523e4e4711fabcb812b1884_d.txt': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/azureml-logs/65_job_prep-tvmps_7318e771e68051077c6cf6cae224b662fda60c42f523e4e4711fabcb812b1884_d.txt?sv=2019-07-07&sr=b&sig=C0i7FZgovm32fXbKrHx3aJM3GPahEDWIZqQVGTMzYcw%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A15%3A37Z&ske=2022-04-09T02%3A25%3A37Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'azureml-logs/65_job_prep-tvmps_f811095d9dad2cc3c9a1c3b2eac109b550c7207bb242244e87ca3f157926e76e_d.txt': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/azureml-logs/65_job_prep-tvmps_f811095d9dad2cc3c9a1c3b2eac109b550c7207bb242244e87ca3f157926e76e_d.txt?sv=2019-07-07&sr=b&sig=mOq14PXTZ6Cu1aMZInemwFwWPyFhmCtLv7ULbVUGJcY%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A15%3A37Z&ske=2022-04-09T02%3A25%3A37Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'azureml-logs/70_driver_log_0.txt': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/azureml-logs/70_driver_log_0.txt?sv=2019-07-07&sr=b&sig=yqRtlM33Vb6QxFz8rLLB0Sc5CeKxRqRqsVAhO7mxStc%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A15%3A37Z&ske=2022-04-09T02%3A25%3A37Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'azureml-logs/70_driver_log_1.txt': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/azureml-logs/70_driver_log_1.txt?sv=2019-07-07&sr=b&sig=2sicbKNlXl1oumhKeOepHBP0XKgyDfr2wnCHCTO%2BnD8%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A15%3A37Z&ske=2022-04-09T02%3A25%3A37Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'azureml-logs/70_driver_log_2.txt': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/azureml-logs/70_driver_log_2.txt?sv=2019-07-07&sr=b&sig=UkSXJANHPn9YFKXwbJ5%2BJx%2FwbSV%2F3lbdGMcELDwGM8k%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A15%3A37Z&ske=2022-04-09T02%3A25%3A37Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A59Z&se=2022-04-08T05%3A50%3A59Z&sp=r',
  'azureml-logs/process_info.json': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/azureml-logs/process_info.json?sv=2019-07-07&sr=b&sig=CZxCUuQOjQDE8Lwj%2BpauhRoSfEN4KexXwcmt3Br79f4%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A15%3A37Z&ske=2022-04-09T02%3A25%3A37Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A59Z&se=2022-04-08T05%3A50%3A59Z&sp=r',
  'azureml-logs/process_status.json': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/azureml-logs/process_status.json?sv=2019-07-07&sr=b&sig=tg2SSSk2EazJqdiBfTtE0hM0ruUi%2Fd3bB915f%2FCBoV8%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A15%3A37Z&ske=2022-04-09T02%3A25%3A37Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A59Z&se=2022-04-08T05%3A50%3A59Z&sp=r',
  'logs/azureml/0_116_azureml.log': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/logs/azureml/0_116_azureml.log?sv=2019-07-07&sr=b&sig=t0Ca5tKpKyBl2kNb%2BP81%2FJbkUEQQXBBTQo4GVi7mxKk%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A51%3A41Z&ske=2022-04-09T03%3A01%3A41Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'logs/azureml/1_89_azureml.log': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/logs/azureml/1_89_azureml.log?sv=2019-07-07&sr=b&sig=FuO7s78Kq3cWdjdtSlFLnjtOyN7LAA1kHRhyrhBjKKc%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A51%3A41Z&ske=2022-04-09T03%3A01%3A41Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'logs/azureml/2_94_azureml.log': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/logs/azureml/2_94_azureml.log?sv=2019-07-07&sr=b&sig=TEk4genRTVf9qfHynj2g0Fk5jhl%2F5xuXOGng42CWUoQ%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A51%3A41Z&ske=2022-04-09T03%3A01%3A41Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'logs/azureml/dataprep/backgroundProcess.log': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/logs/azureml/dataprep/backgroundProcess.log?sv=2019-07-07&sr=b&sig=1wd2x7VpMphKXe7m%2FBhWN3WoWJFEkXz9emTEqtd%2BL2U%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A51%3A41Z&ske=2022-04-09T03%3A01%3A41Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'logs/azureml/dataprep/backgroundProcess_Telemetry.log': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/logs/azureml/dataprep/backgroundProcess_Telemetry.log?sv=2019-07-07&sr=b&sig=VS7Rdo5L2BCLmhnqyrF0aULn3NciAD2CWH2m%2FfSmR%2BM%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A51%3A41Z&ske=2022-04-09T03%3A01%3A41Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'logs/azureml/job_prep_azureml.log': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/logs/azureml/job_prep_azureml.log?sv=2019-07-07&sr=b&sig=%2BzwoFiMorzxGDBbzicLUzF%2BNFMEck3a%2FFzhawjkfphE%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A51%3A41Z&ske=2022-04-09T03%3A01%3A41Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A58Z&se=2022-04-08T05%3A50%3A58Z&sp=r',
  'logs/azureml/sidecar/tvmps_5987e3d904c1b9ce843a5fc9569bf1847092b85d2f71b2906bffe3df00ad9435_d/all.log': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/logs/azureml/sidecar/tvmps_5987e3d904c1b9ce843a5fc9569bf1847092b85d2f71b2906bffe3df00ad9435_d/all.log?sv=2019-07-07&sr=b&sig=cLeJSCQOYn7OmbgcIxMsHQR3DIlcXX1uE97gIkm2x6E%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A51%3A41Z&ske=2022-04-09T03%3A01%3A41Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A59Z&se=2022-04-08T05%3A50%3A59Z&sp=r',
  'logs/azureml/sidecar/tvmps_5987e3d904c1b9ce843a5fc9569bf1847092b85d2f71b2906bffe3df00ad9435_d/task.enter_contexts.log': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/logs/azureml/sidecar/tvmps_5987e3d904c1b9ce843a5fc9569bf1847092b85d2f71b2906bffe3df00ad9435_d/task.enter_contexts.log?sv=2019-07-07&sr=b&sig=L7c7qFc5tM6DMPM3X1C7tGF%2B%2FymGu6KWjGEaB37zgP0%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A51%3A41Z&ske=2022-04-09T03%3A01%3A41Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A59Z&se=2022-04-08T05%3A50%3A59Z&sp=r',
  'logs/azureml/sidecar/tvmps_7318e771e68051077c6cf6cae224b662fda60c42f523e4e4711fabcb812b1884_d/all.log': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/logs/azureml/sidecar/tvmps_7318e771e68051077c6cf6cae224b662fda60c42f523e4e4711fabcb812b1884_d/all.log?sv=2019-07-07&sr=b&sig=ctC1e%2Fxf9Peot5S3W%2BGLGumrSV9i2mWWxQcCioiui%2FU%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A51%3A41Z&ske=2022-04-09T03%3A01%3A41Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A59Z&se=2022-04-08T05%3A50%3A59Z&sp=r',
  'logs/azureml/sidecar/tvmps_7318e771e68051077c6cf6cae224b662fda60c42f523e4e4711fabcb812b1884_d/task.enter_contexts.log': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/logs/azureml/sidecar/tvmps_7318e771e68051077c6cf6cae224b662fda60c42f523e4e4711fabcb812b1884_d/task.enter_contexts.log?sv=2019-07-07&sr=b&sig=YL%2Fzw8mpVtlfFF8cBiSXZNJbrunvRKdV5FJ1N2Z4%2B9w%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A51%3A41Z&ske=2022-04-09T03%3A01%3A41Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A59Z&se=2022-04-08T05%3A50%3A59Z&sp=r',
  'logs/azureml/sidecar/tvmps_f811095d9dad2cc3c9a1c3b2eac109b550c7207bb242244e87ca3f157926e76e_d/all.log': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/logs/azureml/sidecar/tvmps_f811095d9dad2cc3c9a1c3b2eac109b550c7207bb242244e87ca3f157926e76e_d/all.log?sv=2019-07-07&sr=b&sig=Ti4KpuyPGNc%2F22eYpTUBcGRTt0XmxkP%2Bhi6ZlIPAucc%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A51%3A41Z&ske=2022-04-09T03%3A01%3A41Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A59Z&se=2022-04-08T05%3A50%3A59Z&sp=r',
  'logs/azureml/sidecar/tvmps_f811095d9dad2cc3c9a1c3b2eac109b550c7207bb242244e87ca3f157926e76e_d/task.enter_contexts.log': 'https://wu2modtimesmls2858026735.blob.core.windows.net/azureml/ExperimentRun/dcid.81160342-cabb-4253-a774-03c672960252/logs/azureml/sidecar/tvmps_f811095d9dad2cc3c9a1c3b2eac109b550c7207bb242244e87ca3f157926e76e_d/task.enter_contexts.log?sv=2019-07-07&sr=b&sig=8IJ1I03io68yVgS%2Fzbxl5WgRyLn9MjumOST4ZBzga0I%3D&skoid=d75052df-cd47-4b02-aae0-5e3927b54936&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-04-07T18%3A51%3A41Z&ske=2022-04-09T03%3A01%3A41Z&sks=b&skv=2019-07-07&st=2022-04-07T21%3A40%3A59Z&se=2022-04-08T05%3A50%3A59Z&sp=r'},
 'submittedBy': 'Jake Wang'}

**Comment by santiagxf** [comment]
Azure ML SDK v1 doesn't support parameters. Please use MLflow SDK to retrieve them. In fact, MLflow is now the suggested way to log and query runs metrics, parameters, and artifacts across experiments: 

* [Log & view metrics and log files - Azure Machine Learning](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-log-view-metrics)
* [Manage experiments and runs with MLflow - Azure Machine Learning](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-track-experiments-mlflow)
