### ISSUE TITLE
readme.py script doesn't work on Windows

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azureml-examples#146]
**Describe the issue or request**
A clear and concise description or request for enhancement.

**Additional context**

**Comment by martinezgjuan** [comment]
Any updates on when readme.py script will support Windows?

**Comment by lostmygithubaccount** [comment]
@martinezgjuan when someone makes a PR to fix it - it was fixed in a previous PR referenced in the documentation but that never made it in for some reason

**Comment by nick863** [comment]
Fixed in the PR: https://github.com/Azure/azureml-examples/pull/2382
