### ISSUE TITLE
AutoML-Image-Classification Tutorial Notebook Error: MLTable input is invalid.

### ISSUE THREAD

**Issue by HeZhang33** [Azure/azureml-examples#1464]
Hello, 

My colleague and I are having similar issues when runing your image classification and object detection tutorial notebooks. After running the notebooks and submitting the automl-image job runs, we received following errors (similar for classficaiton and detection tasks):

> 
MLTable input is invalid. Failed with visit error: Failed with execution error: error in streaming from input data sources
	VisitError(ExecutionError(StreamError(NotFound)))
=> Failed with execution error: error in streaming from input data sources
	ExecutionError(StreamError(NotFound))

The classification notebook that I followed is this one: 
https://github.com/Azure/azureml-examples/blob/sdk-preview/sdk/jobs/automl-standalone-jobs/automl-image-classification-multiclass-task-fridge-items/automl-image-classification-multiclass-task-fridge-items.ipynb

Please help! Thanks a lot!

He

**Comment by natasha-savic-msft** [comment]
Adding to the thread. For the same notebook it would be good if you added the following line of code to cell 7. When executing the notebook, people will run into an error that the ml table directories do not exist, As such, a `mkdir` operation is useful. 

```
from jsonl_converter import convert_mask_in_VOC_to_jsonl
from pathlib import Path

Path("./data/training-mltable-folder/").mkdir(parents=True, exist_ok=True)
Path("./data/validation-mltable-folder/").mkdir(parents=True, exist_ok=True)

data_path = "./data/odFridgeObjectsMask/"
convert_mask_in_VOC_to_jsonl(data_path, uri_folder_data_asset.path)
```

**Comment by natasha-savic-msft** [comment]
Issue was resolved in the meantime with the release of mltable: [Create Data Assets - Azure Machine Learning | Microsoft Learn](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-create-data-assets?tabs=Python-SDK). 

Please refer to the following documentation to access data assets via SDK v2 and make sure you use the latest AzureML example repository.

**Comment by rjaincc** [comment]
The PR for downloading the dataset and creating MLTable on the fly on user specified location in the PR (https://github.com/Azure/azureml-examples/pull/1911) is merged. Please feel free to raise another issue if you still face the issue.
