### ISSUE TITLE
Endpoint deployment of a computer vision example

### ISSUE THREAD

**Issue by pietz** [Azure/azureml-examples#1553]
I would like to see an example of how a computer vision based model (like object classification or detection) can be deployed to a real-time online endpoint. Specifically, I want to know the best practices and options I have on how to handle the binary input. The following questions revolve in my head:

- Should I provide images by URL?
- Should I provide images by base64?
- Should I provide images as uncompressed pixel tensors?
- Can I provide images as multipart / form-data? (my preferred option)
- Where and how should I handle preprocessing?
- How does it nicely integrate with MLflow

Thanks

**Comment by raduk** [comment]
Hi @pietz,

These notebooks have a section on deployment for mlflow models:

https://github.com/Azure/azureml-examples/blob/main/sdk/python/jobs/automl-standalone-jobs/automl-image-instance-segmentation-task-fridge-items/automl-image-instance-segmentation-task-fridge-items.ipynb

https://github.com/Azure/azureml-examples/blob/main/sdk/python/jobs/automl-standalone-jobs/automl-image-object-detection-task-fridge-items/automl-image-object-detection-task-fridge-items.ipynb

In addition to these examples, you can find detailed documentation here for deployment:

https://learn.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-image-models?tabs=cli#register-and-deploy-model

And for input schema here: https://learn.microsoft.com/en-us/azure/machine-learning/reference-automl-images-schema#data-schema-for-online-scoring

Please let us know if that answers your questions.
