### ISSUE TITLE
ModuleNotFoundError: No module named 'mltable'

### ISSUE THREAD

**Issue by tgokal** [Azure/azureml-examples#1653]
## Which example? Describe the issue

example: working_with_mltable.ipynb
description: ModuleNotFoundError. Cannot install mltable and error occurs from import line in the 3rd cell. I have followed all preceding steps and ran all preceding cells. I cannot run AutoML or Parallel Jobs as a result. 

## Additional context

-

**Comment by PlagueHO** [comment]
I'm seeing this issue as well. Clean install of AzureML with a brand-new Compute Instance.

![image](https://user-images.githubusercontent.com/7589164/193154353-272156b7-9bb5-4a91-9510-791bb7c20888.png)

Confirming `mltable` is installed via pip on the compute instance:
![image](https://user-images.githubusercontent.com/7589164/193154451-2c093f42-cdd6-4b81-b3e8-5de210950460.png)

**Comment by tgokal** [comment]
Confirmed from Engineering that Python 3.10 isn't compatible with `mltable ` yet, but soon will be. It works with Python < 3.9.

**Comment by tgokal** [comment]
Engineering has confirmed that mltable version 0.1.0b4 has been released and now installs on Python 3.10
