### ISSUE TITLE
Designer UI is unresponsive 

### ISSUE THREAD

**Issue by 2asd** [Azure/azureml-examples#1685]
Designer UI is not responsive on any computer for any components. cannot put in parameters, because clicking or typing wont work on the parameter.  Component can be created through drag and drop. However, cannot fill in texts for the parameters of the component.

**Comment by cloga** [comment]
Hi @2asd ,
Are you still encountering this issue? Would you share some screens for this issue?
Thanks.

**Comment by 2asd** [comment]
Hi, @cloga the issue has been resolved by contacting the support team. This was identified as a bug and they have made a change to fix it.
