### ISSUE TITLE
Error after job submission: MLTable input invalid  

### ISSUE THREAD

**Issue by RaikHerrmann** [Azure/azureml-examples#1889]
### Operating System

Windows

### Version Information

Python version: 3.8
Azure-Ai-ML package version: 1.1.0

### Steps to reproduce

Run example (fix minor issues with pathes for ML Table files to successfully run the script until the submission of the job)

### Expected behavior

Job runs successfully

### Actual behavior

Job breaks after about 7 Minutes with error: 

MLTable input is invalid. UserErrorException:
    Message: Encountered user error while fetching data from Dataset. Error: Failed with visit error: Failed with execution error: error in streaming from input data sources
    VisitError(ExecutionError(StreamError(NotFound)))
=> Failed with execution error: error in streaming from input data sources
    ExecutionError(StreamError(NotFound)); Not able to find MLTable file
    InnerException Failed with visit error: Failed with execution error: error in streaming from input data sources
    VisitError(ExecutionError(StreamError(NotFound)))
=> Failed with execution error: error in streaming from input data sources
    ExecutionError(StreamError(NotFound)); Not able to find MLTable file
    ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Encountered user error while fetching data from Dataset. Error: Failed with visit error: Failed with execution error: error in streaming from input data sources\n\tVisitError(ExecutionError(StreamError(NotFound)))\n=> Failed with execution error: error in streaming from input data sources\n\tExecutionError(StreamError(NotFound)); Not able to find MLTable file",
        "inner_error": {
            "code": "BadData",
            "inner_error": {
                "code": "DatasetUserError"
            }
        }
    }
}

### Addition information

ML table folders needed to be created manually / creation by script added manually as script otherwise fails earlier.

**Comment by rjaincc** [comment]
@RaikHerrmann - We have merged the PR for downloading the dataset and creating MLTable on the fly on user specified location in the PR - https://github.com/Azure/azureml-examples/pull/1911. Please feel free to raise another issue if you still face the issue.

**Comment by RaikHerrmann** [comment]
Brilliant, thank you!

***@***.***
Raik Herrmann
Technology Strategist
Data & AI
Office: +49 (89) 31765567
Mobile: +4915158956257
***@***.******@***.***>




Microsoft Deutschland GmbH | Walter-Gropius-Straße 5 | 80807 München
Microsoft - Offizielle Website<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fde-de%3Fql%3D2&data=05%7C01%7CRaik.Herrmann%40microsoft.com%7C834274eeac5f4b32f8d108da8feee405%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637980554036366647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ogNvL%2Fmh29veybc8pnLWxRWWyHS%2FzmH4TSmNq3SjXNA%3D&reserved=0>
Home | News Center Microsoft<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnews.microsoft.com%2Fde-de%2F&data=05%7C01%7CRaik.Herrmann%40microsoft.com%7C834274eeac5f4b32f8d108da8feee405%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637980554036366647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OunPIBj23hP6NxyDbBRa1VLxKrW160IXQR5kNlYrXSo%3D&reserved=0>
Datenschutzerklärung von Microsoft - Microsoft-Datenschutz<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprivacy.microsoft.com%2Fde-DE%2Fprivacystatement&data=05%7C01%7CRaik.Herrmann%40microsoft.com%7C834274eeac5f4b32f8d108da8feee405%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637980554036366647%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9JdwhhHGOal8K0ICyMUvJ2FbMloKN5QVBaDiFSqA%2Fjo%3D&reserved=0>

Geschäftsführer*in: Dr. Marianne Janik (Vorsitzende), Florian Deter, Benjamin O. Orndorff, Keith Dolliver | Amtsgericht München, HRB 70438


Von: Rupal jain ***@***.***>
Gesendet: Montag, 5. Dezember 2022 18:28
An: Azure/azureml-examples ***@***.***>
Cc: Raik Herrmann ***@***.***>; Mention ***@***.***>
Betreff: Re: [Azure/azureml-examples] Error after job submission: MLTable input invalid (Issue #1889)


@RaikHerrmann<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRaikHerrmann&data=05%7C01%7CRaik.Herrmann%40microsoft.com%7Cacad4835d4b341cc563308dad6e600bd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638058580611674345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Rdo3ZiVdvFVSFWJxQWV3NXq%2FP9jwi0URPfEKrCh%2B580%3D&reserved=0> - We have merged the PR for downloading the dataset and creating MLTable on the fly on user specified location in the PR - #1911<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazureml-examples%2Fpull%2F1911&data=05%7C01%7CRaik.Herrmann%40microsoft.com%7Cacad4835d4b341cc563308dad6e600bd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638058580611674345%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d93%2ByNJnuRRZvy%2B5gnOR8i7fY0HWW6OOhlLhV1Be9F0%3D&reserved=0>. Please feel free to raise another issue if you still face the issue.

-
