### ISSUE TITLE
MLflow cli endpoint example out of date with new syntax from breaking changes in yaml (last updated May 11)

### ISSUE THREAD

**Issue by cindyweng** [Azure/azureml-examples#1897]
### Operating System

Windows

### Version Information

latest cli v2 

### Steps to reproduce

https://github.com/Azure/azureml-examples/blob/main/cli/endpoints/online/mlflow/sklearn-deployment.yaml

This yaml is out of date, the model yaml config is wrong. "name" is no longer required when specifying model.

### Expected behavior

That the deployment works based on sklearn-deployment.yml using the cli command `az create deployment`, but it fails. 

### Actual behavior

It fails.

**Comment by pacolecc** [comment]
Below is an example of right yaml configuration file to deploy a MLFlow model on an online endpoint:

$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: sklearn-deployment
endpoint_name: my-endpoint
model: azureml:sklearn-iris-example@latest
instance_type: Standard_DS2_v2
instance_count: 1

**Comment by santiagxf** [comment]
Samples has been updated!
