### ISSUE TITLE
nyc-taxi-mlflow-deployment.yml refers to a folder that doesn't exists

### ISSUE THREAD

**Issue by pacolecc** [Azure/azureml-examples#1899]
### Operating System

Linux

### Version Information

Azure cli v2

### Steps to reproduce

The azureml-example batch endpoint nyc-taxi-mlflow-deployment.yml file, refers to a  ./autolog_nyc_taxi folder that doesn't exist

### Expected behavior

It looks like we need to re-add the folder?

### Actual behavior

code fails because folder doesn't exist

**Comment by santiagxf** [comment]
Thanks for reporting this issue @pacolecc. The problem has been addressed at #1908
