### ISSUE TITLE
Managed Endpoint Samples Dont Work Anymore

### ISSUE THREAD

**Issue by nikhilp0** [Azure/azureml-examples#2097]
### Operating System

Linux

### Version Information

azure-cli: 2.44.1
azure-cli-core: 2.44.1
azure-cli-telemetry: 1.0.8
extensions:
  ml: 2.5.0

### Steps to reproduce

az ml online-endpoint create --name endpoint_name <deployment> -f endpoints/online/managed/sample/endpoint.yml
az ml online-deployment create --name blue --endpoint endpoint_name <deployment> -f endpoints/online/managed/sample/blue-deployment.yml --all-traffic

### Expected behavior

Deployment should be created

### Actual behavior

Fails with user error. Sample uses deprecated python version

```
All traffic will be set to deployment blue once it has been provisioned.
If you interrupt this command or it times out while waiting for the provisioning, you can try to set all the traffic to this deployment later once its has been provisioned.
Check: endpoint <deployment> exists
Uploading onlinescoring (0.0 MBs): 100%|███████████████████████████████████████| 4934/4934 [00:00<00:00, 39428.16it/s]


(UserError) Python versions matching the specification 3.7 have reached or are nearing end-of-life. Python versions 3.8+ are recommended.
Code: UserError
Message: Python versions matching the specification 3.7 have reached or are nearing end-of-life. Python versions 3.8+ are recommended.
Additional Information:Type: ComponentName
Info: {
    "value": "managementfrontend"
}Type: Correlation
Info: {
    "value": {
        "operation": "e0f0e8140af88f7835f583c3275ffd28",
        "request": "f503d842b99053b4"
    }
}Type: Environment
Info: {
    "value": "master"
}Type: Location
Info: {
    "value": "westus2"
}Type: Time
Info: {
    "value": "2023-03-01T18:13:31.3324477+00:00"
}Type: InnerError
Info: {
    "value": {
        "code": "NewRecommendedPythonVersions",
        "innerError": null
    }
}
```

**Comment by aishanibhalla** [comment]
@nikhilp0 Please upgrade your python version as python 3.7 is not supported.

`(UserError) Python versions matching the specification 3.7 have reached or are nearing end-of-life. Python versions 3.8+ are recommended.
Code: UserError`
