### ISSUE TITLE
SOLVED Import error on Azure Machine Learning Studio Notebooks | No module named 'azureml.automl' & No module named 'azureml.train.automl' -  auto-ml-forecasting-bike-share example notebook

### ISSUE THREAD

**Issue by GlennTatum** [Azure/azureml-examples#2275]
### Operating System

Linux

### Version Information

```python

print("You are currently using version", azureml.core.VERSION, "of the Azure ML SDK")

```
You are currently using version 1.49.0 of the Azure ML SDK

Microsoft Azure Machine Learning Studio Notebook Runtime

Python 3.10 - SDK v2

### Steps to reproduce

1. Open a Azure Machine Learning Studio Jupyter Notebook
2. Upload files into Notebook
3. Run all cells in ```azureml-bikes-compute```

Error occurs:

No module named 'azureml.automl'

No module named 'azureml.train.automl'

### Expected behavior

All packages should import correctly.

### Actual behavior

Packages failed to import.

### Addition information

To solve this issue:

1. Open Terminal
2. Run `pip install azure-ai-ml`
3. The Python 3.8 - AzureML runtime will be installed.
4. Switch to the "Python 3.8 - AzureML" runtime.

![Screenshot from 2023-05-14 11-45-25](https://github.com/Azure/azureml-examples/assets/84031833/d9f5e16a-20b6-49d9-9fb3-62b30f648ee9)

**Comment by nick863** [comment]
We have two editions of an SDK; the legacy V1 and V2. The V1 SDK is installed in the Python 3.8 - AzureML environment, and it does not officially support Python versions greater than 3.8. However, the Python 3.10 environment contains the V2 SDK. We have two versions of notebooks, one for V1 and one for V2.
[SDK V1](https://github.com/Azure/azureml-examples/blob/main/v1/python-sdk/tutorials/automl-with-azureml/forecasting-bike-share/auto-ml-forecasting-bike-share.ipynb)
[SDK V2](https://github.com/Azure/azureml-examples/blob/main/sdk/python/jobs/automl-standalone-jobs/automl-forecasting-task-bike-share/auto-ml-forecasting-bike-share.ipynb)
