### ISSUE TITLE
Can't setup an AzureML Dask Cluster 

### ISSUE THREAD

**Issue by murilommen** [Azure/azureml-examples#242]
## Describe the issue

When I follow along the [using-dask tutorial](https://github.com/Azure/azureml-examples/blob/main/tutorials/using-dask/2.eds-at-scale.ipynb) to setup a Dask cluster, I fail to create a new cluster with an odd error that comes up:
`[Errno 113] No route to host`

I tried searching for it, but the results on Google will come with port and routing issues, that I don't know if are directly related to the problem here. Not sure.

## Minimal example

```python
from azureml.core import Workspace

ws = Workspace.from_config()

from azureml.core import Environment

env = Environment.get(workspace=ws, name="AzureML-Dask-CPU")

from dask.distributed import Client
from dask_cloudprovider import AzureMLCluster

cluster = AzureMLCluster(
    ws,
    vm_size="STANDARD_DS5_V2",
    environment_definition=env,
    initial_node_count=10,
    scheduler_idle_timeout=1200,
)

c = Client(cluster)
c
```

## Additional context

- Important to note that I am running all of this inside an Azure ML Compute Instance

**Comment by lostmygithubaccount** [comment]
can you check/post the contents of `portfoward_log.txt` (or something similarly named), which usually contains hints at what's going on

**Comment by lostmygithubaccount** [comment]
i hit a different issue trying to reproduce: 

![image](https://user-images.githubusercontent.com/54814569/98044837-5f12a480-1ddc-11eb-8733-cf5ec1ceea3e.png)

**Comment by murilommen** [comment]
Thanks for the quick reply @lostmygithubaccount 

I was trying to use the curated Dask environment "AzureML-Dask-CPU". When trying to use the same `dask.yml` file I got the exact same error as you.
Possibly something with the libs versions?

**Comment by lostmygithubaccount** [comment]
hello, the `AzureMLCluster` has been deprecated and will be removed in a future release of `dask-cloudprovider`: https://cloudprovider.dask.org/en/latest/azureml.html

the recommended approach is to use the new `AzureVMCluster` - there are some known issues - https://cloudprovider.dask.org/en/latest/azure.html

apologies for the instability
