### ISSUE TITLE
The setup script does not have enough documentation

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-examples#243]
## The script `setup.py` does not have enough documentation

It "does things", people will want to understand more details. It doesn't need to be much, but high-level.

This repo does a really nice job with "Getting started" and "Contents":

https://github.com/microsoft/aml-acceleration-template

e.g. clear instructions on how to use an existing workspace.

**Comment by lostmygithubaccount** [comment]
will not fix until AMLv2, in which setup should be simplified
