### ISSUE TITLE
The CIFAR 10 deepspeed example requires a V100 cluster

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-examples#245]
## The example `train/deepspeed-cifar10.py` requires compute target `gpu-V100-2`

This seems like overkill and makes the examples less accessible. Is it really necessary?

More generally, most subscriptions start out with a V100 quota of **0**. The process for increasing this is painful and lengthy. ~~Most~~ all examples in the repo don't really need such heavy compute.

Also: consider provisioning low-pri compute (at least: mention).

**Comment by dkmiller** [comment]
Rapids **does** require a more recent GPU.

One idea: _carefully separate examples_ requiring heavy GPUs with ones not needing those. The request process is very onerous.

Another alternative: use low-pri (has complications).

**Comment by lostmygithubaccount** [comment]
apparently it is required, a run on K80s failed with CUDA error - will solve this through clearly marking "specialty" examples
