### ISSUE TITLE
Tutorials should have and pass a well-defined content quality bar

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-examples#253]
Some Tutorial notebooks do not have any explanation but only have codes. We need to set up a bar for a notebook to be a part of Tutorials.  

in order to qualify as tutorial, notebook should have:

requirements (what you need to understand / run)
"deliverables" (what you get from running the tutorial)
some kind of written content (not code) talking through what's happening

Some examples:

- https://github.com/Azure/azureml-examples/blob/main/tutorials/using-dask/2.eds-at-scale.ipynb
- https://github.com/Azure/azureml-examples/blob/main/notebooks/train-lightgbm-local.ipynb

**Comment by dkmiller** [comment]
Just added PyTorch Lightning tutorial with more text. Take a look to see!

**Comment by lostmygithubaccount** [comment]
will address this in two parts:

- [ ] update `CONTRIBUTING.md` with well-defined quality bar (for all examples)
- [ ] once agreed on and merged, update tutorials and examples accordingly

**Comment by lostmygithubaccount** [comment]
almost there...will make some final updates this week then ask for review before closing this issue out

**Comment by lostmygithubaccount** [comment]
I think he tutorials now all have excellent READMEs and enough explanation in the notebooks. All of the notebooks should be useful, although some were cut for the sake of quality/relevance - @dkmiller please review tutorials when possible

**Comment by dkmiller** [comment]
@lostmygithubaccount the tutorials all look good! I think this can safely be closed.
