### ISSUE TITLE
Notebooks shouldn't run `pip install`

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-examples#254]
Example:

https://github.com/Azure/azureml-examples/blob/main/tutorials/using-dask/2.eds-at-scale.ipynb

![image](https://user-images.githubusercontent.com/5003801/98049662-03004e00-1de5-11eb-9359-658f7ba35a53.png)

All necessary pip and conda dependencies should be specified in the "base" dependencies file. As part of this, to speed up environment setup, consider using Conda for environment specification (it's much faster with C++ libraries).

If the environment setup time is taking a while and this is slowing down builds, consider publishing a Docker image [as a repo package](https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages).

The Docker image could be another example of "best practices" for users to follow.

**Comment by lostmygithubaccount** [comment]
why not? this was a rule in Azure/MachineLearningNotebooks, but I don't understand why.

we don't want all of the dependencies in the "base" `requirements.txt` if that's what you mean. We want to keep that lightweight and eventually not even require installing Python to run most of these examples. 

For notebooks, which are interactive, a happy medium seemed to be simply pip installing required packages in the notebook, which is often what a data scientist will do

switching to conda would help
