### ISSUE TITLE
PyTorch NLP and other OSS examples

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-examples#255]
We need more examples . Considering increasing popularity of PyTorch compared to TensorFlow, we should add more examples with PyTorch. Considering that NLP is the hottest topic in AI/ML, we should add examples in NLP. 

Also, some feedback from LinkedIn: it would be great if we had tutorials on some popular open source tools, e.g. distributed BERT pretraining, DeepSpeed.

**Comment by dkmiller** [comment]
There's an open ask to add some HuggingFace examples as well.

**Comment by dkmiller** [comment]
Another ask: https://github.com/pytorch/fairseq .

**Comment by lostmygithubaccount** [comment]
closing, please open more specific example asks - there have been a number of new transformers/NLP/other OSS examples added since this was opened
