### ISSUE TITLE
Using `git` for relative paths makes notebooks and code difficult to extract and use individually

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-examples#257]
## Describe it

All the scripts and notebooks in this repo use the [GitPython](https://github.com/gitpython-developers/GitPython) library to determine paths. See for example [2.pytorch-model.ipynb](https://github.com/Azure/azureml-examples/blob/main/tutorials/an-introduction/2.pytorch-model.ipynb), which includes code like:

```python

import git
from pathlib import Path

prefix = Path(git.Repo(".", search_parent_directories=True).working_tree_dir)

# ...

source_directory=prefix.joinpath("code", "train", "pytorch", "cifar10-cnn")
```

This makes it difficult to "copy paste" these tutorials and/or training code into a different repository. It also will not work if anyone uses the "download as zip" functionality GitHub offers:

![image](https://user-images.githubusercontent.com/5003801/98048990-ae100800-1de3-11eb-91e7-d16666275871.png)

## Additional Context

Having "training code" separate from "control code" means that you have to open two separate folders to understand pretty much any example.

**Comment by lostmygithubaccount** [comment]
so option A is hard code the relative path, e.g.:

```python
prefix = Path("../..")
```

everything should work as expected

**Comment by dkmiller** [comment]
@lostmygithubaccount that sounds like a good solution. Makes it much easier for people to extract a single notebook + code.
