### ISSUE TITLE
Create Deployment in the AKS

### ISSUE THREAD

**Issue by banochkabb** [Azure/azureml-examples#2587]
### Operating System

MacOS

### Version Information

Python Version: 3.8.13
azure-ai-ml package version: 1.9.0

### Steps to reproduce

I try to deploy llama2 model on existing AKS using python azureml. I run the following code:

```
REQUEST_TIMEOUT_MS = 90000

subscription_id = "<internal_id>"
resource_group = "<internal_rg>"
workspace = "<internal_ws>"

from azureml.core import Workspace

ws = Workspace.get(name=workspace,
               subscription_id=subscription_id,
               resource_group=resource_group)

aks_target = ws.compute_targets['test-aks']
aks_target

from azure.ai.ml import MLClient
from azure.ai.ml.entities import (
    KubernetesOnlineEndpoint,
    OnlineEndpoint,
    ManagedOnlineDeployment,
    Model,
    Environment,
    CodeConfiguration,
    KubernetesOnlineDeployment
)
from azure.identity import DefaultAzureCredential

uri = "models:/llama-13b-chat/1"
deploy_path = "deployment_config.json"  # {"computeType": "aks", "computeTargetName": "test-aks"}
test_config = {'deploy-config-file': deploy_path}

ml_client = MLClient(
    DefaultAzureCredential(), subscription_id, resource_group, workspace
)

endpoint_name = "llama-13b-chat-endpoint-k8s-2"

# create an online endpoint
endpoint = KubernetesOnlineEndpoint(
    name = endpoint_name, 
    description="Test endpoint for model",
    auth_mode="key"
)
ml_client.online_endpoints.begin_create_or_update(endpoint).result()

deployment = KubernetesOnlineDeployment(
    name="test-aks",
    endpoint_name=endpoint_name,
    model='llama-13b-chat:1',
    instance_count=1,
)
ml_client.begin_create_or_update(deployment).result()
```

### Expected behavior

Model deployment created

### Actual behavior

I got error saying that "cannot deploy Kubernetes model to Managed endpoint". If I replace KubernetesDeployment with ManagedDeployment, it tries to allocate a new instance, however I need to deploy model on existing AKS without allocating new machines. 

What am I doing wrong?

**Comment by mobaniha** [comment]
Can you confirm that you have enough cpu quota for the deployment? 
https://learn.microsoft.com/en-us/azure/machine-learning/how-to-troubleshoot-online-endpoints?view=azureml-api-2&tabs=cli#cpu-quota

**Comment by banochkabb** [comment]
yes, but I want to deploy it to existing Kubernetes Cluster

**Comment by santiagxf** [comment]
Hi @banochkabb! Sorry for the delay on the response. I just run across with your comment. It looks you are mixing `azureml-sdk` (what we call our SDK v1) with `azure-ai-ml` (what we call our SDK v2). Notice that those SDKs allow you to interface with different objects on our platform, it's not just the version of the SDK.

Kubernetes clusters on V1 (AksCluster) is considered legacy. Foundational models is only available using V2 constructs, and that includes the type of compute used. On V2, we have `KubernetesCompute`. 

To unblock you:

* Migrate from `AksClusters` (V1) to `KubernetesCompute` (V2). 
* Upgrade your deployment code to use all SDK V2 constructs (using only `azure-ai-ml` package.

To learn more about the differences between V1 and V2 in terms of Kubernetes please see: [Introduction to Kubernetes compute target in Azure Machine Learning](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-attach-kubernetes-anywhere?view=azureml-api-2).
