### ISSUE TITLE
How to use PythonScript Step on top of Dask Cluster 

### ISSUE THREAD

**Issue by arnabbiswas1** [Azure/azureml-examples#273]
## What example? Describe it

I have created a dask cluster in the Azure ML Workspace using dask_cloudprovider. I am looking for an example, where I can use a [PythonScriptStep](https://docs.microsoft.com/en-us/python/api/azureml-pipeline-steps/azureml.pipeline.steps.python_script_step.pythonscriptstep?view=azure-ml-py) (or in general [AzureML Pipeline](https://docs.microsoft.com/en-us/azure/machine-learning/concept-ml-pipelines)) and submit the job to the dask cluster. 

Google search lead me to [this](https://github.com/drabastomek/GTC/blob/master/SJ_2020/workshop/1_Setup/Setup.ipynb). But, corresponding example here does not create a AzureML Pipeline step.

The question is **is it really possible to do this?**

**Comment by lostmygithubaccount** [comment]
there are a few options and none of them are good:

1. simply use your PythonScriptStep to create and use `dask_cloudprovider.AzureMLCluster` as you would locally - i.e. use a small compute target simply for orchestration, which creates the larger dask cluster and uses it in the code

2. modify https://github.com/danielsc/azureml-and-dask - which the `dask_cloudprovider.AzureMLCluster` code is based off of - to setup the Dask cluster as part of the script submission, and use it like that. You wouldn't directly be using `dask-cloudprovider`. I haven't done this in a while, but the general flow should work

Again, neither of these are good options. v2 will natively support Dask jobs in pipelines @jpe316 fyi

**Comment by lostmygithubaccount** [comment]
particularly this file: https://github.com/danielsc/azureml-and-dask/blob/master/batch/dask/startDask.py

you can view the notebook for submission, which passes in a script to run as an argument and runs it

![image](https://user-images.githubusercontent.com/54814569/98709501-4b64c200-2337-11eb-87d3-202fc7d2db52.png)

**Comment by arnabbiswas1** [comment]
I tried option 1 of yours. Not sure if it is the right way of doing things.

In short I am doing the following:

1. Create Dask Cluster from my laptop (ideally I should do it on a Azure Compute Instance. This is failing now because of the port forwarding issue).
2. Get the environment details and scheduler FQDN/Port from the AMLCluster object.
3. Create a PythonScriptStep object. Pass environment details to it as RunConfiguration() and compute_target as the Dask Cluster name. This makes sure that my Python Script gets executed on the Dask Cluster using the corresponding environment.
4. Pass scheduler FQDN & Port to the Python Script as an argument.
5. Within the Script, create a Dask Client using the scheduler FQDN & Port.

This is how my code looks like:

1. Create a Dask Cluster using AzureMLCluster() API

```
amlcluster = AzureMLCluster(ws,
                            vm_size="STANDARD_D1",
                            environment_definition=ws.environments['AzureML-Dask-CPU'], 
                            initial_node_count=0, 
                            scheduler_idle_timeout=3600,
                            vnet='my_vnet',
                            subnet='subnet1',
                            vnet_resource_group='resource_group',
                            ct_name="arnabdask",
)
```

2. Create a RunConfiguration object pointing to the dask environment inside dask cluster

```
run_config = RunConfiguration()
run_config.environment = amlcluster.environment_definition
```
4. Create a PythonScriptStep object with compute_target as the dask cluster, runconfig created above. Pass `amlcluster.scheduler_ip_port` as an argument of the Python Script passed to the PythonScriptStep.

```
prep_step = PythonScriptStep(name='prepare_step',
                             script_name="prepare_data.py",
                             arguments=[amlcluster.scheduler_ip_port, input_ds.as_named_input('my_data').as_mount()],
                             source_directory=SOURCE_DIR,
                             compute_target="arnabdask",
                             runconfig=run_config
                             )
```

5. Create an experiment and submit.

```
experiment = Experiment(workspace=ws, name="my_exp")
pipeline = Pipeline(ws, steps=[prep_step])
run = experiment.submit(pipeline)
run.wait_for_completion()
```

6. Here is the dummy code for the `prepare_data.py`

```

scheduler_url = sys.argv[1]
mounted_input_path = sys.argv[2]

c = Client(scheduler_url)

dd = dd.read_parquet(mounted_input_path)
.....
```

**Comment by lostmygithubaccount** [comment]
this is another promising option: http://mpi.dask.org/en/latest/
