### ISSUE TITLE
Langchain Azure Mistral example doesn't run — AttributeError: 'ChatMessage' object has no attribute 'model_dump'

### ISSUE THREAD

**Issue by antoremin** [Azure/azureml-examples#3022]
### Operating System

MacOS

### Version Information

sdk/python/foundation-models/mistral/langchain.ipynb

Python Version: Python 3.9.11
azure-ai-ml package version:  - 
mistralai version: mistralai-0.0.11
langchain-mistralai version: langchain-mistralai-0.0.4

### Steps to reproduce

1. Download the notebook
2. Enter your Azure Mistral Large deployment credentials
3. Run the notebook

### Expected behavior

cell with content `chat_llm_chain.predict(human_input="Hi there my friend")` outputs model reply 

### Actual behavior

cell with content `chat_llm_chain.predict(human_input="Hi there my friend")` returns error `AttributeError: 'ChatMessage' object has no attribute 'model_dump'`

**Comment by santiagxf** [comment]
Hi @antoremin. Can you please do a fresh install? Looks like some references may be old in your environment.

```bash
pip install -U langchain langchain_mistralai mistralai
```

**Comment by antoremin** [comment]
Hey @santiagxf thanks, that worked!
