### ISSUE TITLE
Azure ML Monitoring - Bring your own production data - endpoint_deployment_id needed?

### ISSUE THREAD

**Issue by hmrc87** [Azure/azureml-examples#3128]
### Describe your suggestion

Hi @ahughes-msft,
in https://github.com/Azure/azureml-examples/blob/8cf7249115c2d27dfcc0a572d3ab50669247a793/cli/monitoring/README.md you describe how one can use his/her own production data.

It refers to cli/monitoring/model-monitoring-with-collected-data.yaml 

Why do I need to specify an **endpoint_deployment_id** for the monitoring target when I am in fact not using any deployed endpoint. Is the field optional? I see that it is mutually exclusive with the model_id but not sure what the impact is in this case.

**Comment by ahughes-msft** [comment]
Hi @hmrc87 - Great call out, thank you. I'll go ahead and update the example to reflect that endpoint_deployment_id is optional in the case where you are providing your own data.

**Comment by hmrc87** [comment]
Thanks for the quick response @ahughes-msft. Additionally it says: Model_id and endpoint_deployment_id are mutually exclusive. In which case would I use the model_id? The endpoint_deployment_id I would use so that the UI will show the endpoint requests, right? But what about the model_id?

When I bring my own production data but have the model hosted in Azure ML, would it make sense to add the model_id in that case?

**Comment by ahughes-msft** [comment]
Hi @hmrc87, the model_id is not used by our backend service, so you don't need to provide it for any situation. We will work on removing it from the UI/CLI/SDK.
