### ISSUE TITLE
MLflow 1.13 probably broke deployment

### ISSUE THREAD

**Issue by akshaya-a** [Azure/azureml-examples#318]
https://github.com/Azure/azureml-examples/runs/1618089261?check_suite_focus=true

@trangevi 

https://github.com/mlflow/mlflow/pull/3419/files

**Comment by akshaya-a** [comment]
yeah @trangevi the logging statement is guaranteed to bork out: https://github.com/mlflow/mlflow/blob/master/mlflow/azureml/__init__.py#L413

@eedeleon fyi

**Comment by eedeleon** [comment]
https://github.com/mlflow/mlflow/pull/3922

**Comment by lostmygithubaccount** [comment]
@akshaya-a @eedeleon looks resolved, thanks for investigating! will close this issue
