### ISSUE TITLE
Customize Compute Instance Script Example Not Working 

### ISSUE THREAD

**Issue by moirarenata** [Azure/azureml-examples#3291]
### Operating System

Windows

### Version Information

azure-cli: 2.59.0
azure-cli-core: 2.59.0
azure-cli-telemetry: 1.1.0
extensions:
  ml: 2.26.1

### Steps to reproduce

Followed the steps [to create a customized compute instance here](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-customize-compute-instance?view=azureml-api-2) and used the [example creation script](https://github.com/Azure/azureml-examples/blob/main/setup/setup-ci/setup-custom-conda-env.sh).

### Expected behavior

Create a working compute instance with the 'envname' environment and have the numpy package installed within that environment

### Actual behavior

Compute instance creation succeeded but the commands in the creation script did not run properly. Got a "conda: command not found" in the logs.

**Comment by lucasfijen** [comment]
I was running into the same issue, adding `source /anaconda/etc/profile.d/conda.sh` in the script before the firsttime you call conda should fix it.

I created a PR for this bug #3321
