### ISSUE TITLE
deepspeed example broken

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azureml-examples#346]
## Which example? Describe the issue

example: deepspeed workflow
description: started failing last week

## Additional context

- needs investigation

**Comment by lostmygithubaccount** [comment]
@awan-10 could you take a look at this? 

it has been failing with the same thing starting last week:

```
Traceback (most recent call last):
  File "train.py", line 171, in <module>
    data[0].to(model_engine.local_rank),
RuntimeError: Device index must not be negative
```

example logs: https://github.com/Azure/azureml-examples/runs/1796664414?check_suite_focus=true

**Comment by awan-10** [comment]
@lostmygithubaccount - Sorry, I cannot access the experiment logs. Can you attach them here? 

Did something change recently in AML? We have not made any changes to DeepSpeed that should trigger this.

**Comment by awan-10** [comment]
@lostmygithubaccount -- We found the issue and are fixing it now. Will take a day to fix/push new PR and Curated Environment.

**Comment by lostmygithubaccount** [comment]
thanks!

**Comment by awan-10** [comment]
@lostmygithubaccount - please trigger the tests again. We have fixed the error and the CE is live now with deepspeed=0.3.11.

**Comment by lostmygithubaccount** [comment]
they run automatically, test has been green for the last 2 runs - thanks! closing this issue 

https://github.com/Azure/azureml-examples/actions?query=workflow%3Atrain-deepspeed-cifar-job
