### ISSUE TITLE
Deepspeed example no CUDA on image and env vars not set

### ISSUE THREAD

**Issue by aminsaied** [Azure/azureml-examples#357]
## Which example? Describe the issue

example: Deepspeed
description: Two issues:

- Example uses a curated environment but run fails with CUDA not found error
- Environment variables are not set for local rank

### CUDA error (no workaround)

The deepspeed example (cifar) uses curated environment

```
env = Environment.get(ws, name="AzureML-DeepSpeed-0.3-GPU")
```

but run fails with

```
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

Running on STANDARD_NV6.

### Environment variables (work around available)

Script makes use of local rank in multiple places. By the looks of it these are intended to be set via the command line (passed as arguments to the ScriptRunConfig). The global rank is passed this way, but not the local rank.

I added

```
"--local_rank", "$OMPI_COMM_WORLD_LOCAL_RANK",
```

It might be cleaner / more consistent to make use "set_environment_variables_for_nccl_backend" code as we are doing in other places e.g. https://azure.github.io/azureml-web/docs/cheatsheet/distributed-training

**Comment by lostmygithubaccount** [comment]
@awan-10
