### ISSUE TITLE
This repo needs a "modern" R example

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-examples#363]
## What example? Describe it

Azure ML gets a steady stream of questions around best practices for running R in Azure ML. Since we no longer recommend `RScriptStep`, we need a good example which showcases:

- Docker-based environment
- Using `CommandStep`
- MLFlow SDK for logging

**Comment by lostmygithubaccount** [comment]
this brings up an interesting tangential question of multi-language organization in this repo - should we have top level separation somewhere for `R`, `python`, `julia`, etc?

**Comment by lostmygithubaccount** [comment]
and if so where exactly - I'm tempted for now to simply consider `R` etc. a "tool" for the purposes of organization. also it might be good to start with a tutorial

**Comment by dkmiller** [comment]
I would say no: I don't think top-level org for languages makes sense. I think e.g. folders

`r-basic-data-and-logging`

`julia-basic-data-and-logging`

or something like that under tutorials makes more sense.

**Comment by lostmygithubaccount** [comment]
for tutorials I'd think

`using-r` and `using-julia`

but was more asking under `workflows`

**Comment by dkmiller** [comment]
Ahh, workflows vs. tutorials isn't a big distinction, doesn't matter much. And agree, `using-r` is better than what I suggested.

**Comment by lostmygithubaccount** [comment]
another random problem - `using-r` would cause a conflict with `using-rapids` because whoever setup the workflow logic made it overly complicated, should fix this - will await a PR for R and make necessary adjustments

**Comment by lostmygithubaccount** [comment]
R examples present in 2.0 CLI, closing
