### ISSUE TITLE
rapids tutorial broken

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azureml-examples#379]
## Which example? Describe the issue

example: rapids tutorial
description: started failing ~16 hours ago

## Additional context

- not sure if coincidence, deepspeed tutorial started failing around same time

**Comment by lostmygithubaccount** [comment]
cc: @zronaghi

**Comment by lostmygithubaccount** [comment]
likely hyperdrive (Azure ML) issue unrelated to RAPIDS

**Comment by lostmygithubaccount** [comment]
no V100 capacity for the test subscription in eastus, closing

**Comment by zronaghi** [comment]
Thanks for the update @lostmygithubaccount, was this resolved? I see the tests are still failing

**Comment by lostmygithubaccount** [comment]
not yet, waiting for updates internally - worst case scenario should auto resolve at some point
