### ISSUE TITLE
Live collaboration in jupyter notebooks

### ISSUE THREAD

**Issue by jadeshi** [Azure/azureml-examples#392]
Hi,
I was wondering if it was currently possible for two users to collaborate live on an Azure ML jupyter notebook, and if not, if this is a feature that's under consideration. Basically I'm looking for a "Google spreadsheets" kind of behavior, where if two users have the same notebook open, when I type/execute some code, it updates instantly in real time on the other user's screen.

**Comment by AbeOmor** [comment]
Hi, @jadeshi This is actually a feature we have been testing internally for quite some time now to make sure we have a great customer experience. It is great to see users like you are interested and looking forward to this experience! 

Currently, we don't have a concrete timeline of when this feature will roll out to ALL customers but you can watch this video to see how it will work in the AzureML Notebooks component: https://youtu.be/AAj-Fz0uCNk?t=523 

And also read more about it in our blog:  https://techcommunity.microsoft.com/t5/azure-ai/improving-collaboration-and-productivity-in-azure-machine/ba-p/2160906
