### ISSUE TITLE
PyTorch Lightning example

### ISSUE THREAD

**Issue by aminsaied** [Azure/azureml-examples#395]
Let's add an example of distributed training with lightning.

Include deepspeed plugin?

**Comment by lostmygithubaccount** [comment]
they do exist: https://github.com/Azure/azureml-examples/tree/main/tutorials/using-pytorch-lightning

**Comment by NA-Dev** [comment]
The link is no longer valid. Is there a replacement somewhere? I couldn't find where it moved to.
