### ISSUE TITLE
aml_utils.py scrip is not available.

### ISSUE THREAD

**Issue by ruizhuanguw** [Azure/azureml-examples#415]
## aml_utils.py scrip is not available. 

description: Line 11-13 of azureml-examples/workflows/train/transformers/glue/1-aml-finetune-job.py describes we need to run 'aml_utils.py' to create two environment. However, the script is not available in the repo.

**Comment by lostmygithubaccount** [comment]
it seems like it is instead included in the code itself, and the docstring should simply remove the mention of an external script - assigning @aminsaied to confirm

**Comment by aminsaied** [comment]
Yup that's right. Fix is to remove that from the docstring. Thanks @ruizhuanguw for raising!
