### ISSUE TITLE
CLI examples are Linux-only

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-examples#519]
## how-to-deploy-declarative-safe-rollout-online-endpoints.sh (e.g.)

The CLI examples are only usable in Linux machines, which is a bit frustrating since many Microsoft customers use Windows.

Suggest parallel examples targeting PowerShell (Core).

**Comment by lostmygithubaccount** [comment]
they're intended to be as agnostic as possible - in the documentation (for setup and training) there is nothing bash/linux-specific (you're not really intended to read the `.sh` files, but rather the corresponding articles on docs.microsoft.com)

this will also improve over time. wanted to avoid needing to maintain duplicate CLI scripts for PowerShell, but if necessary we can

**Comment by lostmygithubaccount** [comment]
e.g. (MSFT internal only) https://review.docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli?branch=release-build-2021-azureml and https://review.docs.microsoft.com/en-us/azure/machine-learning/how-to-train-cli?branch=release-build-2021-azureml

**Comment by lostmygithubaccount** [comment]
there is a reference to `$job_id` which is bash-specific but that will be removed in the near-future

**Comment by dkmiller** [comment]
Fair points. If we can keep the "snippets" as OS-agnostic as possible, it doesn't matter too much whether they're in `.sh` or `.ps1` files.
