### ISSUE TITLE
Include most significant examples in root-level README

### ISSUE THREAD

**Issue by dkmiller** [Azure/azureml-examples#520]
## Describe it

For people returning to this repo, the root-level README looks pretty minimal:

![image](https://user-images.githubusercontent.com/5003801/118567018-e2b53280-b729-11eb-9f9e-039255302ad5.png)

to the point where multiple people have asked me if the repo is dead.

Suggestion: include (at least some of) the Python and CLI example links in the root-level README.

## Additional context

Also, suggest to _not_ link to the `.github` directory &mdash; that's an implementation detail that end users shouldn't have to care about.

**Comment by lostmygithubaccount** [comment]
@dkmiller as in remove the row from the table, or just the hyperlink?

**Comment by dkmiller** [comment]
@lostmygithubaccount I suggest removing the row and hyperlink. Both are confusing to users.

**Comment by lostmygithubaccount** [comment]
closing this issue. we are using this repository as the central location for examples, and will work within docs & the studio to ensure the best examples are prominent rather than maintaining in the README
