### ISSUE TITLE
Batch Score Example Fails (v 2.0.0a1)

### ISSUE THREAD

**Issue by ezwiefel** [Azure/azureml-examples#529]
When trying to create a batch scoring endpoint using `how-to-batch-score.sh` as a guide - specifically this line:
https://github.com/Azure/azureml-examples/blob/658116133c41d9a9fbc4e443ee0a054168b3e60f/cli/how-to-batch-score.sh#L5

I'm getting a failure - for a missing environment:
```bash
azureuser@nbvm-v2:~/cloudfiles/code/azureml-examples/cli$ az ml endpoint create --type batch --file endpoints/batch/create-batch-endpoint.yml
Command group 'ml endpoint' is experimental and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Code: UserError
Message: Environment is missing.

azureuser@nbvm-v2:~/cloudfiles/code/azureml-examples/cli$ az extension list
[
  {
    "experimental": true,
    "extensionType": "whl",
    "name": "ml",
    "path": "/opt/az/extensions/ml",
    "preview": false,
    "version": "2.0.0a1"
  }
]
```

**Comment by tracychms** [comment]
This is a known issue, the fix is under deployment, currently available in some of the regions. To bypass this error now, please update extension of "https://github.com/Azure/azureml-examples/blob/main/cli/endpoints/batch/autolog_nyc_taxi/conda.yml" to .**yaml**.
