### ISSUE TITLE
update pytorch cifar to use datastore upload

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azureml-examples#577]
## Which example? Describe the issue

example: cli/jobs/pytorch/cifar-distributed/job.yml and corresponding train.sh script
description: update to upload to datastore instead of using local data

## Additional context

-

**Comment by buswrecker** [comment]
+1 on all examples; We should use DataSets / DataStore concepts more with the new CLI v2 - it shoulds a more powerful integration with other parts of Azure; specifically Synapse / DataLake Gen 2 etc. 

Is there a roadmap for CLI v2.0 to support this?
