### ISSUE TITLE
migrate AutoML notebooks from MachineLearningNotebooks

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azureml-examples#609]
## What example? Describe it

example: automl examples in Azure/MachineLearningNotebooks
description: some consolidation/cleanup is needed, but generally can migrate the examples as-is with testing setup

## Additional context

-

**Comment by rtanase** [comment]
@lostmygithubaccount this has been addressed. Can we close it now?

**Comment by lostmygithubaccount** [comment]
fixed via #615
