### ISSUE TITLE
Blob does not exist - batch-score.sh

### ISSUE THREAD

**Issue by luisquintanilla** [Azure/azureml-examples#624]
## Which example? 

example: cli/batch-score.sh
description: mnist data blob https://pipelinedata.blob.core.windows.net/sampledata/mnist does not exist

## Additional context

This example is in the documentation and users have reported issues MicrosoftDocs/azure-docs#78474

**Comment by luisquintanilla** [comment]
@tracychms You're tagged in the doc issue as well. Adding this issue here as well for tracking purposes.

**Comment by tracychms** [comment]
Thanks @luisquintanilla , will update to use this open dataset: https://docs.microsoft.com/en-us/azure/open-datasets/dataset-mnist?tabs=azureml-opendatasets

**Comment by lostmygithubaccount** [comment]
I've personally had issues using the MNIST data from Azure Open Datasets - the formatting didn't seem standard. An alternate is here: https://azuremlexamples.blob.core.windows.net/datasets/mnist

used in this notebook, for instance: https://github.com/Azure/azureml-examples/blob/main/notebooks/blob-adls-numpy/1.read-write.ipynb

**Comment by tracychms** [comment]
this blob also doesn't exist.

**Comment by lostmygithubaccount** [comment]
the gzipped files are in there, e.g. https://azuremlexamples.blob.core.windows.net/datasets/mnist/train-images-idx3-ubyte.gz

although might not be what you're looking for, not sure how you're reading the data in

**Comment by tracychms** [comment]
the images are restored. sample works fine now.
