### ISSUE TITLE
parser_f() got an unexpected keyword argument 'storage_options'

### ISSUE THREAD

**Issue by ruizhuanguw** [Azure/azureml-examples#637]
I tried to reproduce the the same code of https://github.com/Azure/azureml-examples/blob/main/notebooks/blob-adls-pandas/1.read-write.ipynb
However, I got error "TypeError: parser_f() got an unexpected keyword argument 'storage_options'" in the fourth code cell
`df = pd.read_csv(f"az://{container_name}/iris.csv", storage_options=storage_options);
`

**Comment by lostmygithubaccount** [comment]
requires `pandas>=1.2` and `adlfs` installed - unexpected keyword argument means the pandas version is old, if you can an error about no ABFS/azure filesystem that's the adlfs install
