### ISSUE TITLE
Pipeline sample referencing a compute cluster not exists

### ISSUE THREAD

**Issue by ttthree** [Azure/azureml-examples#897]
https://github.com/Azure/azureml-examples/blob/218cc4c83d708f17504845e0ebffe8b84ebef431/cli/jobs/pipelines-with-components/nyc_taxi_data_regression/job.yml#L26

In the documents users are always asked to create compute named "cpu-cluster", and this sample will just fail because it uses a different compute name: cpu-cluster-lg

https://docs.microsoft.com/en-us/azure/machine-learning/how-to-create-component-pipelines-cli

Here is what i got:

![image](https://user-images.githubusercontent.com/18907/140603155-c95581a4-7fb3-4c22-8bd2-075fdd83dacf.png)

**Comment by cloga** [comment]
#899 I have created this PR to do the fix.

**Comment by cloga** [comment]
Fixed.
