### ISSUE TITLE
online-deployment issue "The Managed Inference service creation is taking longer than our normal time"

### ISSUE THREAD

**Issue by bhushangholave** [Azure/azureml-examples#903]
## Example
example: az ml online-deployment create --name blue --endpoint advanced-ner-endpoint-demo -f deployment.yml --all-traffic
description: creating deployment in existing endpoint

## Additional context
output:-
Creating or updating online_deployments
Check: endpoint advanced-endpoint exists
The deployment request bhushan-workspace-advanced-ner-endpoint-demo-8612672 was accepted. ARM deployment URI for reference:
https://ms.portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/overview/id/%2Fsubscriptions%2F2b044625-9119-453a-8f50-53426430883b%2
Registering model version (ad2f42d3-xxxx-xxxx-be9f-2e20ef135c16 1 )  Done (1s)
Registering code version (c665e43f-xxxx-xxxx-a98d-a84911248e91 1 )  Done (1s)
Registering environment version (32890045-xxxx-48d3-a43c-6f2ec0323d08 1 )  Done (6s)
Creating deployment blue   ................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Code: ResourceDeploymentFailure
Message: The resource operation completed with terminal provisioning state 'Failed'.
Exception Details:      (DeploymentTimedOut) The Managed Inference service creation is taking longer than our normal time.

-

**Comment by paledger** [comment]
@bhushangholave Sorry for delayed response. I see that you created the same endpoint/deployment combo in centralindia, eastus, and westus. I'm seeing those deployments mostly failing with user error container. Can you provide below info?
- region
- timestamp of call / ARM Service Request ID (can be found in the Operation Details of the deployment link you posted, which I don't have access to)

Thanks!

**Comment by bhushangholave** [comment]
@paledger Than you for the response. Since this was little urgent from me I have opened issue with azure-cli-extension team and got resolution that this is related to pip dependencies / conda environment creation issue.

**Comment by paledger** [comment]
@bhushangholave what was the issue with your environment? Is it resolved now?

**Comment by bhushangholave** [comment]
issue was with conda environment creation was not getting completed and environment creation was stuck. I tried pin pip<=20.2.4 to use old resolver that ignores some of the conflicts and it worked.

**Comment by pragasv** [comment]
Any update on this ?

**Comment by bhushangholave** [comment]
@paledger Yes this is resolved. Pip version and dependencies needs to be in sync.

**Comment by bhushangholave** [comment]
Closing this thread
