### ISSUE TITLE
AutoML object detection on large training datasets

### ISSUE THREAD

**Issue by marcmm** [Azure/azureml-examples#940]
It looks like data needs to be downloaded to local compute before training can begin. Is there any way to reduce the time taken by this step, like preprocessing the data and consuming data in batches from a remote storage mount rather than trying to download the data?

On my large dataset download is taking a really long time:

Start downloading image files
Downloading image files took 2375.97 seconds
Downloading pretrained model weights to local disk.

**Comment by raduk** [comment]
Hi @marcmm, 

We recently added a way to stream data instead of downloading: https://learn.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-image-models?tabs=python#streaming-image-files-from-storage

Please give it a try and let us know how it goes.
